services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - ~/data/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 50
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - ~/data/wp:/var/www/html #look here for site files
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - ~/data/wp:/var/www/html #look here for site files
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 90s
    restart: always

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
      - default
    volumes:
      - redis_data:/data
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  redis_data:
