services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - ~/data/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 50
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - ~/data/wp:/var/www/html #look here for site files
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - ~/data/wp:/var/www/html #look here for site files
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 90s
    restart: always

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
      - default
    volumes:
      - redis_data:/data
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    ports:
      - "21:21"
      - "1998-2002:1998-2002"
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - ~/data/wp:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "21"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    ports:
      - "8080:9001"
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - ~/data/wp:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "timeout 3s bash -c '</dev/tcp/localhost/9001'"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  grafana:
    build:
      context: ./requirements/bonus/grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - default
    env_file: 
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana
    depends_on:
      - mariadb
      - wordpress
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always

volumes:
  redis_data:
  grafana_data:
  grafana_logs:
